language: php
php:
  - 5.3.2
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - "pyrus upgrade -f -p pear2.php.net/PEAR2_Pyrus_Developer"
  - curl http://install.onionphp.org/ | bash
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - php onion bundle

script: phpunit
