language: php
php:
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - pear channel-discover pear.corneltek.com
  - pear channel-discover components.ez.no
  - pear install -a ezc/ConsoleTools
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - php onion install
  - composer install --dev

script: phpunit
