language: php
php:
  - 5.3.2
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - "pyrus upgrade -f -p pear2.php.net/PEAR2_Pyrus_Developer"
  - curl http://install.onionphp.org/ | bash
  - onion bundle

script: phpunit
